/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class CoulombJFrame extends javax.swing.JFrame {

    /**
     * Creates new form CoulombJFrame
     */
    public CoulombJFrame() {
        initComponents();
        setBounds(300, 100, 794, 550);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxUnidadCarga = new javax.swing.JComboBox<>();
        btnActualizar = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnVolver = new javax.swing.JButton();
        btnCalcular = new javax.swing.JToggleButton();
        txtResultado = new javax.swing.JTextField();
        cbxDistancia = new javax.swing.JComboBox<>();
        txtElevadoCarga = new javax.swing.JTextField();
        txtFuerza = new javax.swing.JTextField();
        txtR = new javax.swing.JTextField();
        txtCarga = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxUnidadCarga.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "µC", "nC", "kC" }));
        jPanel1.add(cbxUnidadCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 160, -1, 30));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/ACTUALIZAR.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, 40));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/LIMPIAR.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 140, 40));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/VOLVER.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 140, 40));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/CALCULAR.png"))); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 140, 40));

        txtResultado.setEditable(false);
        jPanel1.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 180, 30));

        cbxDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Km", "M", "Cm" }));
        jPanel1.add(cbxDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 210, -1, 30));
        jPanel1.add(txtElevadoCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 30, 30));
        jPanel1.add(txtFuerza, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 260, 110, 30));
        jPanel1.add(txtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 210, 110, 30));
        jPanel1.add(txtCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, 100, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Calculadora2.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 793, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Inicio x = new Inicio();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtCarga.setText(null);
        txtElevadoCarga.setText(null);
        txtFuerza.setText(null);
        txtR.setText(null);
        txtResultado.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            double carga = Double.valueOf(txtCarga.getText());
            double elevadoCarga = Math.pow(10, Double.valueOf(txtElevadoCarga.getText()));
            double distancia = Double.valueOf(txtR.getText());

            String dist = (String) cbxDistancia.getSelectedItem();
            if ("Cm".equals(dist)) {
                distancia = distancia / 100;
            }
            
            if ("M".equals(dist)) {
                distancia = distancia;
            }

            if ("Km".equals(dist)) {
                distancia = distancia * 1000;
            }
            
            double distanciacuadrado = Math.pow(distancia, 2);
            double cargaelevado =  carga * elevadoCarga;
            
            double fuerza = Double.valueOf(txtFuerza.getText());
            double resultado = (fuerza * distanciacuadrado) / (9.0e9 * cargaelevado);

            txtResultado.setText(String.valueOf(resultado));
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacíos");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
        // TODO add your handling code here:
        String Uq1 = (String) cbxUnidadCarga.getSelectedItem();
        if ("µC".equals(Uq1)) {
            txtElevadoCarga.setText("-6");
        }
        if ("kC".equals(Uq1)) {
            txtElevadoCarga.setText("3");
        }
        if ("nC".equals(Uq1)) {
            txtElevadoCarga.setText("-9");
        }

    }//GEN-LAST:event_btnActualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CoulombJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CoulombJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CoulombJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CoulombJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CoulombJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDistancia;
    private javax.swing.JComboBox<String> cbxUnidadCarga;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtCarga;
    private javax.swing.JTextField txtElevadoCarga;
    private javax.swing.JTextField txtFuerza;
    private javax.swing.JTextField txtR;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
