/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import javax.swing.JOptionPane;

/**
 *
 * @author Majo
 */
public class DistanciaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form DistanciaJFrame
     */
    public DistanciaJFrame() {
        initComponents();
        imgRepelen1.setVisible(false);
        imgRepelen2.setVisible(false);
        imgAtraen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        cbxDistancia = new javax.swing.JComboBox<>();
        btnVolver = new javax.swing.JButton();
        btnLimpiar = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JToggleButton();
        txtElevadoQ2 = new javax.swing.JTextField();
        imgAtraen = new javax.swing.JLabel();
        imgRepelen2 = new javax.swing.JLabel();
        imgRepelen1 = new javax.swing.JLabel();
        txtR = new javax.swing.JTextField();
        txtElevadoQ1 = new javax.swing.JTextField();
        txtF = new javax.swing.JTextField();
        cbxUnidadQ1 = new javax.swing.JComboBox<>();
        cbxUnidadQ2 = new javax.swing.JComboBox<>();
        cbxQ2 = new javax.swing.JComboBox<>();
        cbxQ1 = new javax.swing.JComboBox<>();
        txtQ2 = new javax.swing.JTextField();
        txtQ1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cbxDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "M", "Km", "Cm" }));
        jPanel1.add(cbxDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 170, -1, 30));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/VOLVER.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel1.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 460, 140, 40));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/LIMPIAR.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel1.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 410, 140, 40));

        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/ACTUALIZAR.png"))); // NOI18N
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel1.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 360, 140, 40));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/CALCULAR.png"))); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel1.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 210, 140, 40));
        jPanel1.add(txtElevadoQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 180, 30, 30));

        imgAtraen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/q1yq2serepelen.png"))); // NOI18N
        jPanel1.add(imgAtraen, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        imgRepelen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/q1yq2seatraen2.png"))); // NOI18N
        jPanel1.add(imgRepelen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 350, -1, -1));

        imgRepelen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/q1yq2seatraen.png"))); // NOI18N
        jPanel1.add(imgRepelen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 340, 330, 140));

        txtR.setEditable(false);
        jPanel1.add(txtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 170, 180, 30));
        jPanel1.add(txtElevadoQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 130, 30, 30));
        jPanel1.add(txtF, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 260, 100, 30));

        cbxUnidadQ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "µC", "nC", "kC" }));
        jPanel1.add(cbxUnidadQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 160, -1, -1));

        cbxUnidadQ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "µC", "nC", "kC" }));
        jPanel1.add(cbxUnidadQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, -1, -1));

        cbxQ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        jPanel1.add(cbxQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 210, -1, -1));

        cbxQ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        jPanel1.add(cbxQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 160, -1, -1));
        jPanel1.add(txtQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 110, 30));
        jPanel1.add(txtQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, 110, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Calculadora3.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 790, 510));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
        Inicio x = new Inicio();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtElevadoQ2.setText(null);
        txtElevadoQ1.setText(null);
        txtF.setText(null);
        txtQ1.setText(null);
        txtQ2.setText(null);
        txtR.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    String Uq1 = (String) cbxUnidadQ1.getSelectedItem();
    String Uq2 = (String) cbxUnidadQ2.getSelectedItem();
        
    if ("µC".equals(Uq1)){
        txtElevadoQ1.setText("-6");
    }
    if ("µC".equals(Uq2)){
        txtElevadoQ2.setText("-6");
    }
    if ("kC".equals(Uq1)){
        txtElevadoQ1.setText("3");
    }
    if ("kC".equals(Uq2)){
        txtElevadoQ2.setText("3");
    }
    if ("nC".equals(Uq1)){
        txtElevadoQ1.setText("-9");
    }
    if ("nC".equals(Uq2)){
        txtElevadoQ2.setText("-9");
    }

    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
        // TODO add your handling code here:
        try {
            double Q1 = Double.valueOf(txtQ1.getText());
            double Q2 = Double.valueOf(txtQ2.getText());
            double l = Double.valueOf(txtElevadoQ1.getText());
            double o = Double.valueOf(txtElevadoQ2.getText());
            double ElevadoQ1 = Math.pow(10, l);
            double ElevadoQ2 = Math.pow(10, o);
            double F = Double.valueOf(txtF.getText());
            double K = 9.0e9;
            String Pq1 = String.valueOf(cbxQ1.getSelectedItem());
            String Pq2 = String.valueOf(cbxQ2.getSelectedItem());

            //operaciones
            double a = (Q1 * ElevadoQ1) * (Q2 * ElevadoQ2);
            double h = K * a;
            double b = (h / F);
            double c = Math.sqrt(b);
            String R = (String) cbxDistancia.getSelectedItem();

            String Uq1 = (String) cbxUnidadQ1.getSelectedItem();
            String Uq2 = (String) cbxUnidadQ2.getSelectedItem();

            if ("Cm".equals(R)) {
                c = c * 100;
                txtR.setText(String.valueOf(c));
            }
            if ("M".equals(R)) {
                c = c;
                txtR.setText(String.valueOf(c));
            }
            if ("Km".equals(R)) {
                c = c * 1000;
                txtR.setText(String.valueOf(c));
            }

            if ("+".equals(Pq1) && "+".equals(Pq2)) {
                imgRepelen1.setVisible(true);
                imgRepelen2.setVisible(false);
                imgAtraen.setVisible(false);
            } else if ("-".equals(Pq1) && "+".equals(Pq2)) {
                imgAtraen.setVisible(true);
                imgRepelen1.setVisible(false);
                imgRepelen2.setVisible(false);
            } else if ("+".equals(Pq1) && "-".equals(Pq2)) {
                imgAtraen.setVisible(true);
                imgRepelen1.setVisible(false);
                imgRepelen2.setVisible(false);
            } else if ("-".equals(Pq1) && "-".equals(Pq2)) {
                imgRepelen2.setVisible(true);
                imgAtraen.setVisible(false);
                imgRepelen1.setVisible(false);
            }
        } catch (Exception ex) {
            JOptionPane.showMessageDialog(null, "No pueden haber campos vacíos");
        }
    }//GEN-LAST:event_btnCalcularActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DistanciaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DistanciaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DistanciaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DistanciaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new DistanciaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JToggleButton btnCalcular;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDistancia;
    private javax.swing.JComboBox<String> cbxQ1;
    private javax.swing.JComboBox<String> cbxQ2;
    private javax.swing.JComboBox<String> cbxUnidadQ1;
    private javax.swing.JComboBox<String> cbxUnidadQ2;
    private javax.swing.JLabel imgAtraen;
    private javax.swing.JLabel imgRepelen1;
    private javax.swing.JLabel imgRepelen2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtElevadoQ1;
    private javax.swing.JTextField txtElevadoQ2;
    private javax.swing.JTextField txtF;
    private javax.swing.JTextField txtQ1;
    private javax.swing.JTextField txtQ2;
    private javax.swing.JTextField txtR;
    // End of variables declaration//GEN-END:variables
}
