/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package proyecto;

import java.text.DecimalFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Franco
 */
public class FuerzaJFrame extends javax.swing.JFrame {

    /**
     * Creates new form FuerzaJFrame
     */
    public FuerzaJFrame() {
        initComponents();
        setBounds(300, 100, 794, 550);
        imgRepelen1.setVisible(false);
        imgRepelen2.setVisible(false);
        imgAtraen.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jInternalFrame1 = new javax.swing.JInternalFrame();
        jPanel2 = new javax.swing.JPanel();
        imgAtraen = new javax.swing.JLabel();
        imgRepelen2 = new javax.swing.JLabel();
        imgRepelen1 = new javax.swing.JLabel();
        btnVolver = new javax.swing.JButton();
        btnActualizar = new javax.swing.JButton();
        chkRes = new javax.swing.JCheckBox();
        txtQ1 = new javax.swing.JTextField();
        txtR = new javax.swing.JTextField();
        txtQ2 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        cbxQ1 = new javax.swing.JComboBox<>();
        cbxQ2 = new javax.swing.JComboBox<>();
        cbxUnidadQ1 = new javax.swing.JComboBox<>();
        cbxUnidadQ2 = new javax.swing.JComboBox<>();
        cbxDistancia = new javax.swing.JComboBox<>();
        txtElevadoQ1 = new javax.swing.JTextField();
        txtElevadoQ2 = new javax.swing.JTextField();
        txtReaccion = new javax.swing.JTextField();
        txtResultado = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        btnCalcular = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        btnCalcular1 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);

        jInternalFrame1.setBorder(new javax.swing.border.MatteBorder(null));
        jInternalFrame1.setTitle("Calculadora de Fuerza");

        javax.swing.GroupLayout jInternalFrame1Layout = new javax.swing.GroupLayout(jInternalFrame1.getContentPane());
        jInternalFrame1.getContentPane().setLayout(jInternalFrame1Layout);
        jInternalFrame1Layout.setHorizontalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jInternalFrame1Layout.setVerticalGroup(
            jInternalFrame1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        imgAtraen.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/q1yq2serepelen.png"))); // NOI18N
        jPanel2.add(imgAtraen, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        imgRepelen2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/q1yq2seatraen2.png"))); // NOI18N
        jPanel2.add(imgRepelen2, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 350, -1, -1));

        imgRepelen1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/q1yq2seatraen.png"))); // NOI18N
        jPanel2.add(imgRepelen1, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 340, 330, 140));

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/VOLVER.png"))); // NOI18N
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        jPanel2.add(btnVolver, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 450, 140, 40));

        btnActualizar.setFont(new java.awt.Font("Tahoma", 0, 1)); // NOI18N
        btnActualizar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/ACTUALIZAR.png"))); // NOI18N
        btnActualizar.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        btnActualizar.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        btnActualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnActualizarActionPerformed(evt);
            }
        });
        jPanel2.add(btnActualizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 350, 140, 40));

        chkRes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                chkResActionPerformed(evt);
            }
        });
        jPanel2.add(chkRes, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 260, -1, 40));
        jPanel2.add(txtQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 110, -1));
        jPanel2.add(txtR, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 250, 60, 30));
        jPanel2.add(txtQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 210, 110, -1));

        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Redondear resultado");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, -1, 40));

        cbxQ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        jPanel2.add(cbxQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        cbxQ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "+", "-" }));
        jPanel2.add(cbxQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 210, -1, -1));

        cbxUnidadQ1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "µC", "nC", "kC" }));
        jPanel2.add(cbxUnidadQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 160, -1, -1));

        cbxUnidadQ2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "C", "µC", "nC", "kC" }));
        jPanel2.add(cbxUnidadQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, -1, -1));

        cbxDistancia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Km", "M", "Cm" }));
        jPanel2.add(cbxDistancia, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 250, -1, 30));

        txtElevadoQ1.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtElevadoQ1, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 140, 30, -1));

        txtElevadoQ2.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        txtElevadoQ2.setAlignmentX(1.0F);
        jPanel2.add(txtElevadoQ2, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 190, 30, 30));

        txtReaccion.setEditable(false);
        txtReaccion.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtReaccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 230, 170, 30));

        txtResultado.setEditable(false);
        txtResultado.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        jPanel2.add(txtResultado, new org.netbeans.lib.awtextra.AbsoluteConstraints(580, 170, 170, -1));

        btnLimpiar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/LIMPIAR.png"))); // NOI18N
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });
        jPanel2.add(btnLimpiar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 140, 40));

        btnCalcular.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/CALCULAR.png"))); // NOI18N
        btnCalcular.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcularActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcular, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 310, 140, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/Calculadora.png"))); // NOI18N
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        btnCalcular1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Fondo/CALCULAR.png"))); // NOI18N
        btnCalcular1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCalcular1ActionPerformed(evt);
            }
        });
        jPanel2.add(btnCalcular1, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 300, 140, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 794, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 794, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 510, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap(161, Short.MAX_VALUE)
                    .addComponent(jInternalFrame1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(349, Short.MAX_VALUE)))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
    cbxDistancia.setSelectedItem("Km");
    cbxQ1.setSelectedItem("+");
    cbxQ2.setSelectedItem("+");
    cbxUnidadQ1.setSelectedItem("C");
    cbxUnidadQ2.setSelectedItem("C");
    txtQ1.setText(null);
    txtQ2.setText(null);
    txtElevadoQ1.setText(null);
    txtElevadoQ2.setText(null);
    txtR.setText(null);
    txtReaccion.setText(null);
    txtResultado.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnCalcularActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcularActionPerformed
    try {
    double q1 = Double.valueOf(txtQ1.getText());
    double q2 = Double.valueOf(txtQ2.getText());
    double Eq1 = Double.valueOf(txtElevadoQ1.getText());
    double Eq2 = Double.valueOf(txtElevadoQ2.getText());
    double r = Double.valueOf(txtR.getText());
    String Uq1 = (String) cbxUnidadQ1.getSelectedItem();
    String Uq2 = (String) cbxUnidadQ2.getSelectedItem();
    String Pq1 = String.valueOf(cbxQ1.getSelectedItem());
    String Pq2 = String.valueOf(cbxQ2.getSelectedItem());
    String dist = (String) cbxDistancia.getSelectedItem();
    double resPotQ1 = Math.pow(10,Eq1);
    double resPotQ2 = Math.pow(10,Eq2);
    double EK = Math.pow(10,9);
    double K = 9.0*EK;
    
    if ("Cm".equals(dist)){
        r = r/100;
    }
    if ("M".equals(dist)){
        r = r;
    }
    if ("Km".equals(dist)){
        r = r*1000;
    }
    
    if ("+".equals(Pq1) && "+".equals(Pq2)) {
        txtReaccion.setText("Se Repelen");
        imgRepelen1.setVisible(true);
        imgRepelen2.setVisible(false);
        imgAtraen.setVisible(false);
    }
    else if ("-".equals(Pq1) && "+".equals(Pq2)) {
        txtReaccion.setText("Se Atraen");
        imgAtraen.setVisible(true);
        imgRepelen1.setVisible(false);
        imgRepelen2.setVisible(false);
    }
    else if ("+".equals(Pq1) && "-".equals(Pq2)) {
        txtReaccion.setText("Se Atraen");
        imgAtraen.setVisible(true);
        imgRepelen1.setVisible(false);
        imgRepelen2.setVisible(false);
    }
    else if ("-".equals(Pq1) && "-".equals(Pq2)) {
        txtReaccion.setText("Se Repelen");
        imgRepelen2.setVisible(true);
        imgAtraen.setVisible(false);
        imgRepelen1.setVisible(false);
    }
    double resultado = 0;
        double a = 0;
        double b = 0;
        double c = 0;
        a = (q1*resPotQ1)*(q2*resPotQ2);
        b = r * r;
        c = (K * (a/b));
        if (chkRes.isSelected()) {
            c = Math.round(c);
        }
        txtResultado.setText(String.valueOf(c));
    } catch(Exception ex){
        JOptionPane.showMessageDialog(null, "No pueden haber campos vacíos");
    }
        
    }//GEN-LAST:event_btnCalcularActionPerformed

    private void chkResActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_chkResActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_chkResActionPerformed

    private void btnActualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnActualizarActionPerformed
    String Uq1 = (String) cbxUnidadQ1.getSelectedItem();
    String Uq2 = (String) cbxUnidadQ2.getSelectedItem();
        
    if ("µC".equals(Uq1)){
        txtElevadoQ1.setText("-6");
    }
    if ("µC".equals(Uq2)){
        txtElevadoQ2.setText("-6");
    }
    if ("kC".equals(Uq1)){
        txtElevadoQ1.setText("3");
    }
    if ("kC".equals(Uq2)){
        txtElevadoQ2.setText("3");
    }
    if ("nC".equals(Uq1)){
        txtElevadoQ1.setText("-9");
    }
    if ("nC".equals(Uq2)){
        txtElevadoQ2.setText("-9");
    }
    
    
    
    }//GEN-LAST:event_btnActualizarActionPerformed

    private void btnCalcular1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCalcular1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnCalcular1ActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    Inicio x = new Inicio();
        x.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FuerzaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FuerzaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FuerzaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FuerzaJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FuerzaJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnActualizar;
    private javax.swing.JButton btnCalcular;
    private javax.swing.JButton btnCalcular1;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnVolver;
    private javax.swing.JComboBox<String> cbxDistancia;
    private javax.swing.JComboBox<String> cbxQ1;
    private javax.swing.JComboBox<String> cbxQ2;
    private javax.swing.JComboBox<String> cbxUnidadQ1;
    private javax.swing.JComboBox<String> cbxUnidadQ2;
    private javax.swing.JCheckBox chkRes;
    private javax.swing.JLabel imgAtraen;
    private javax.swing.JLabel imgRepelen1;
    private javax.swing.JLabel imgRepelen2;
    private javax.swing.JInternalFrame jInternalFrame1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField txtElevadoQ1;
    private javax.swing.JTextField txtElevadoQ2;
    private javax.swing.JTextField txtQ1;
    private javax.swing.JTextField txtQ2;
    private javax.swing.JTextField txtR;
    private javax.swing.JTextField txtReaccion;
    private javax.swing.JTextField txtResultado;
    // End of variables declaration//GEN-END:variables
}
