/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package proyecto;

import Cargas.Calculos;
import Cargas.Cargas;
import Pintar.Lineas;
import java.text.DecimalFormat;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JOptionPane;
import static javax.swing.JOptionPane.showConfirmDialog;

/**
 *
 * @author fredy-18
 */
public class VentanaPrincipal extends JFrame implements Runnable{
    private final int MAXIMO_CARGAS = 200;
    Cargas cargas[] = new Cargas[MAXIMO_CARGAS];
    /**
     * Creates new form VentanaPrincipal
     */
Thread repint = new Thread(this);
    public VentanaPrincipal() {
        initComponents();
        signo = '-';         
        jlm1.setVisible(false);
        jlm2.setVisible(false);
        repint.start();
        repint.suspend();
        nroCarga.setVisible(false);      
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenu2 = new javax.swing.JPopupMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jd1 = new javax.swing.JDialog();
        jPanel1 = new javax.swing.JPanel();
        jButton5 = new javax.swing.JButton();
        jLabel8 = new javax.swing.JLabel();
        jtV = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        help = new javax.swing.JDialog();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel3 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        btnAyuda = new javax.swing.JButton();
        jp1 = new javax.swing.JPanel();
        jlm1 = new javax.swing.JLabel();
        jlm2 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jlcarga = new javax.swing.JLabel();
        fondo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        j = new javax.swing.JLabel();
        i = new javax.swing.JLabel();
        parenti2 = new javax.swing.JLabel();
        parenti = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        nroCarga = new javax.swing.JLabel();
        fuerzaT = new javax.swing.JLabel();
        angulo = new javax.swing.JLabel();
        jToggleButton4 = new javax.swing.JToggleButton();
        jToggleButton3 = new javax.swing.JToggleButton();
        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        btnVolver = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPopupMenu2.addPopupMenuListener(new javax.swing.event.PopupMenuListener() {
            public void popupMenuCanceled(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeInvisible(javax.swing.event.PopupMenuEvent evt) {
            }
            public void popupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {
                jPopupMenu2PopupMenuWillBecomeVisible(evt);
            }
        });

        jMenuItem1.setText("Cambiar valor Carga");
        jMenuItem1.setEnabled(false);
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jPopupMenu2.add(jMenuItem1);

        jd1.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                jd1WindowClosing(evt);
            }
        });

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Cambio Valor Carga"));
        jPanel1.setLayout(null);

        jButton5.setText("Aceptar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5);
        jButton5.setBounds(60, 70, 90, 23);

        jLabel8.setText("Valor");
        jPanel1.add(jLabel8);
        jLabel8.setBounds(20, 30, 30, 14);
        jPanel1.add(jtV);
        jtV.setBounds(50, 30, 120, 20);

        jLabel9.setText("ej: 2.43E-9  ó 3.655");
        jPanel1.add(jLabel9);
        jLabel9.setBounds(50, 50, 120, 14);

        jd1.getContentPane().add(jPanel1, java.awt.BorderLayout.CENTER);

        help.setTitle("Ayuda");
        help.setMinimumSize(new java.awt.Dimension(300, 300));
        help.addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                helpWindowClosing(evt);
            }
        });
        help.getContentPane().setLayout(null);

        jPanel3.setLayout(null);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/uso.PNG"))); // NOI18N
        jPanel3.add(jLabel5);
        jLabel5.setBounds(0, 0, 430, 470);

        jTabbedPane1.addTab("Como Usar", jPanel3);

        help.getContentPane().add(jTabbedPane1);
        jTabbedPane1.setBounds(0, 0, 450, 525);
        jTabbedPane1.getAccessibleContext().setAccessibleName("como Usar");
        jTabbedPane1.getAccessibleContext().setAccessibleDescription("");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Simulador fuerza eléctrica");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        setResizable(false);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowClosing(java.awt.event.WindowEvent evt) {
                formWindowClosing(evt);
            }
        });
        getContentPane().setLayout(null);

        btnAyuda.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/AYUDA.jpg"))); // NOI18N
        btnAyuda.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnAyuda.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAyudaActionPerformed(evt);
            }
        });
        getContentPane().add(btnAyuda);
        btnAyuda.setBounds(410, 10, 120, 30);

        jp1.setBorder(javax.swing.BorderFactory.createMatteBorder(3, 3, 3, 3, new java.awt.Color(0, 0, 0)));
        jp1.setComponentPopupMenu(jPopupMenu2);
        jp1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jp1.setOpaque(false);
        jp1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jp1MouseClicked(evt);
            }
            public void mousePressed(java.awt.event.MouseEvent evt) {
                jp1MousePressed(evt);
            }
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                jp1MouseReleased(evt);
            }
        });
        jp1.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseDragged(java.awt.event.MouseEvent evt) {
                jp1MouseDragged(evt);
            }
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                jp1MouseMoved(evt);
            }
        });
        jp1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jp1KeyReleased(evt);
            }
        });
        jp1.setLayout(null);

        jlm1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mira.png"))); // NOI18N
        jp1.add(jlm1);
        jlm1.setBounds(20, 430, 20, 20);

        jlm2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/mira.png"))); // NOI18N
        jp1.add(jlm2);
        jlm2.setBounds(50, 430, 20, 20);
        jp1.add(jLabel10);
        jLabel10.setBounds(0, 30, 900, 440);

        getContentPane().add(jp1);
        jp1.setBounds(10, 50, 900, 470);
        getContentPane().add(jlcarga);
        jlcarga.setBounds(890, 0, 30, 10);

        fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/cuadriculas2.PNG"))); // NOI18N
        getContentPane().add(fondo);
        fondo.setBounds(10, 50, 900, 470);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder("Fuerza Total(x,y)"));
        jPanel2.setLayout(null);

        jTextField1.setText("0");
        jTextField1.setEnabled(false);
        jPanel2.add(jTextField1);
        jTextField1.setBounds(30, 20, 90, 18);

        jLabel2.setFont(new java.awt.Font("Tahoma", 2, 18)); // NOI18N
        jLabel2.setText("+");
        jPanel2.add(jLabel2);
        jLabel2.setBounds(140, 20, 20, 20);

        jTextField2.setText("0");
        jTextField2.setEnabled(false);
        jPanel2.add(jTextField2);
        jTextField2.setBounds(160, 20, 90, 18);

        j.setFont(new java.awt.Font("Vani", 1, 18)); // NOI18N
        j.setText("j");
        jPanel2.add(j);
        j.setBounds(260, 10, 10, 40);

        i.setFont(new java.awt.Font("Vijaya", 1, 36)); // NOI18N
        i.setText("i");
        jPanel2.add(i);
        i.setBounds(130, 10, 20, 40);

        parenti2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parenti2.setText(")");
        jPanel2.add(parenti2);
        parenti2.setBounds(270, 10, 10, 30);

        parenti.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        parenti.setText("(");
        jPanel2.add(parenti);
        parenti.setBounds(17, 10, 10, 30);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("N");
        jPanel2.add(jLabel1);
        jLabel1.setBounds(280, 10, 14, 30);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(220, 49, 0, 0);

        nroCarga.setText("Número de cargas:");
        getContentPane().add(nroCarga);
        nroCarga.setBounds(280, 530, 130, 20);

        fuerzaT.setText("567");
        getContentPane().add(fuerzaT);
        fuerzaT.setBounds(280, 550, 100, 20);

        angulo.setText("567");
        getContentPane().add(angulo);
        angulo.setBounds(540, 30, 10, 0);

        jToggleButton4.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jToggleButton4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/m.png"))); // NOI18N
        jToggleButton4.setText("Medir");
        jToggleButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton4.setFocusable(false);
        jToggleButton4.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton4.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton4);
        jToggleButton4.setBounds(10, 530, 57, 47);

        jToggleButton3.setFont(new java.awt.Font("Tahoma", 0, 8)); // NOI18N
        jToggleButton3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/eliminar.png"))); // NOI18N
        jToggleButton3.setText("Eliminar");
        jToggleButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton3.setFocusable(false);
        jToggleButton3.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton3.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton3);
        jToggleButton3.setBounds(80, 530, 61, 47);

        jToggleButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/negativa.png"))); // NOI18N
        jToggleButton1.setSelected(true);
        jToggleButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton1);
        jToggleButton1.setBounds(210, 540, 57, 33);

        jToggleButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/positiva.png"))); // NOI18N
        jToggleButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jToggleButton2.setFocusable(false);
        jToggleButton2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToggleButton2.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        jToggleButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jToggleButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jToggleButton2);
        jToggleButton2.setBounds(150, 540, 57, 33);

        btnVolver.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/VOLVER.png"))); // NOI18N
        btnVolver.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        btnVolver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVolverActionPerformed(evt);
            }
        });
        getContentPane().add(btnVolver);
        btnVolver.setBounds(770, 530, 130, 40);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagenes/FondoA.jpg"))); // NOI18N
        getContentPane().add(jLabel3);
        jLabel3.setBounds(0, 0, 922, 580);

        setSize(new java.awt.Dimension(938, 617));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jp1MouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp1MouseReleased
        int x = evt.getX();
        int y =evt.getY();         
        JLabel jp= new JLabel();
        if(!evt.isMetaDown()){
           if(topeCargas < MAXIMO_CARGAS){
              if(jToggleButton1.isSelected()|| jToggleButton2.isSelected() || jToggleButton1.isSelected()){
                  cargas[topeCargas]= new Cargas(valorCarga, x, y, signo, jp, imagenC ); //  ob.pintarCarga(jPanel1.getGraphics(), cargas[topeCargas].getX(),cargas[topeCargas].getY(), jPanel1,cargas[topeCargas].getSibno());
                  topeCargas ++; 
                  nroCarga.setText("Nro de cargas: "+(topeCargas));
             }
           }
           else{
               JOptionPane.showMessageDialog(jp1,"Se ha llegado al maximo de C");
           }
        }
        
    }//GEN-LAST:event_jp1MouseReleased

    private void jp1MouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp1MouseMoved
        for (int i = 0; i < topeCargas; i++) {// se calcula la fuerza con tansolo pasar el puntero del mause por sobre de una carga
            if(evt.getX() >= cargas[i].getJlbael().getX() &&  
               evt.getX() <= cargas[i].getJlbael().getX()+20&&
               evt.getY() >= cargas[i].getJlbael().getY() && 
               evt.getY() <= cargas[i].getJlbael().getY()+20){
                 Calculos calculos = new Calculos(cargas, topeCargas, i);
                 calculos.Calculos();
 
                  jTextField1.setText(""+valorAprocimado(String.valueOf(calculos.getDirI())));
                 jTextField2.setText(""+valorAprocimado(String.valueOf(calculos.getDirJ()))); 
                 jlcarga.setVisible(true);
                 jlcarga.setBounds(cargas[i].getX() ,cargas[i].getY()+30 , 180, 20);
                 jlcarga.setText(""+cargas[i].getCarga()+"C");
                 fuerzaT.setText("F: "+valorAprocimado(String.valueOf(calculos.getFuerzaTotal()))+"N");
                 
                DecimalFormat df = new DecimalFormat ( "#### 00.0");// debuel una decima despues del punto
                angulo.setText("Angulo: "+df.format(calculos.getAngulo())+"°");
               
              break;
            }
            else jlcarga.setVisible(false);
           
        }        
 // TODO add your handling code here:
    }//GEN-LAST:event_jp1MouseMoved

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        jd1.setBounds(200, 100, 200, 150);
        jd1.setVisible(true);
        this.setEnabled(false);
    }//GEN-LAST:event_jMenuItem1ActionPerformed

    private void jp1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp1MouseClicked

    
    }//GEN-LAST:event_jp1MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
      try{
         double valor =Double.parseDouble(jtV.getText());
         cargas[idCarga].setCarga(Math.abs(valor));
         jtV.setText(null);
         this.setEnabled(true);
         jd1.dispose();
      }catch(Exception ex){
          JOptionPane.showMessageDialog(null,"El valor que desea\nregistrar no es valido");
      }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jp1MouseDragged(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp1MouseDragged
        bx = evt.getX();
        by = evt.getY();        
        // la variables que estan dentro de los condiconales se hacen verdad cuando se presiona clic
//        y dejan de ser verdad cuando sueltal el clic es decir mientras se tiene presionado el clic y se esta micineod el puntero del mouse
           if(clikMira1){  // si se ha dado clic  sobre al jlabel de la mira de sinta metrica    si es verdadero entra
               jLabel10.repaint();
               jlm1.setBounds(bx-10, by-10, 20, 20); 
               jToggleButton1.setSelected(false); 
                jToggleButton2.setSelected(false);
               jToggleButton3.setSelected(false);
           }
           else if(clikMira2){  // si se ha dado click  sobre al jlabel de la mira de sinta metrica      
              jLabel10.repaint();
              jlm2.setBounds(bx-10, by-10, 20, 20);
              jToggleButton1.setSelected(false); 
              jToggleButton2.setSelected(false);
             jToggleButton3.setSelected(false);
           }
           else if(clickCarga){// sobre al guna carga esto se ha
                cargas[idCarga].getJlbael().setBounds(bx-10, by-10, 24, 24);
                cargas[idCarga].setX(bx-10);
                cargas[idCarga].setY(by-10);               
                Calculos calculos = new Calculos(cargas, topeCargas, idCarga);
                calculos.Calculos();
                 jTextField1.setText(""+valorAprocimado(String.valueOf(calculos.getDirI())));
                 jTextField2.setText(""+valorAprocimado(String.valueOf(calculos.getDirJ())));                 
                jlcarga.setBounds(bx-10 ,by+20 , 180, 20);
//                fuerzaT.setText("F: "+calculos.getFuerzaTotal()+"N");
                DecimalFormat df = new DecimalFormat ( "#### 00.0");
                angulo.setText("Angulo: "+df.format(calculos.getAngulo())+"°");
                fuerzaT.setText("F: "+valorAprocimado(String.valueOf(calculos.getFuerzaTotal()))+"N");
                jToggleButton1.setSelected(false); 
                 jToggleButton2.setSelected(false);
                 jToggleButton3.setSelected(false);
               
           }   
    }//GEN-LAST:event_jp1MouseDragged

    private void jp1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jp1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_jp1KeyReleased

    private void jp1MousePressed(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jp1MousePressed
        
       if(!evt.isMetaDown()){// comprueva si damos click izquierdo
          bx = evt.getX();
          by = evt.getY();
          clickCarga = false;
          clikMira2 = false;
          clikMira1 = false;         
          if(bx>=jlm1.getX() && bx<=jlm1.getX()+20 && by>=jlm1.getY() && by<=jlm1.getY()+20 ){// si se hadado clic sobtre una jlb de la miara
            clikMira1 = true;                     
           }
           else if(bx>=jlm2.getX() && bx<=jlm2.getX()+20 && by>=jlm2.getY() && by<=jlm2.getY()+20 ){//                    ""
            clikMira2 = true;                         
           }
       else if (clikMira2 == false && clikMira1 == false) {// comprueva si se ha dado clic sobre una caraga
            for (int i = 0; i < topeCargas; i++) {
             if(evt.getX() >= cargas[i].getJlbael().getX() &&  
                  evt.getX() <= cargas[i].getJlbael().getX()+20 &&
                  evt.getY() >= cargas[i].getJlbael().getY() && 
                  evt.getY() <= cargas[i].getJlbael().getY()+20){    
                  idCarga = i;// capturamos la posicion de la caraga en el vector
                  if(jToggleButton3.isSelected() && !evt.isMetaDown()){// Si el voton eliminar esta seleccionado eliminamos la carga
                     jp1.remove(cargas[i].getJlbael());// la quitamos del panel
                     cargas[i]=cargas[topeCargas-1];
                     cargas[topeCargas-1]=null;
                     topeCargas--;
                     jp1.repaint();// limpiamoas el panel
                     jlcarga.setVisible(false);
                     nroCarga.setText("Nro de cargas: "+(topeCargas));
                  }
                  else{
                   clickCarga = true;
                 
                  }
              break;
            } 
         } 
        }
       }
       else{// si se ha dado clic derecho para que aparesca el jpopu 
       jMenuItem1.setEnabled(false);// 
        for (int i = 0; i < topeCargas; i++) {
            if(evt.getX() >= cargas[i].getJlbael().getX() &&  
               evt.getX() <= cargas[i].getJlbael().getX()+20&&
               evt.getY() >= cargas[i].getJlbael().getY() && 
               evt.getY() <= cargas[i].getJlbael().getY()+20){
                  idCarga=i;
                 jMenuItem1.setEnabled(true);//si se a dado clic sobre una carga hacemos editable el el Menu iten 1
              break;
            
            }
        }
       }
    }//GEN-LAST:event_jp1MousePressed

    private void jPopupMenu2PopupMenuWillBecomeVisible(javax.swing.event.PopupMenuEvent evt) {//GEN-FIRST:event_jPopupMenu2PopupMenuWillBecomeVisible
 
    }//GEN-LAST:event_jPopupMenu2PopupMenuWillBecomeVisible

    private void jToggleButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton1ActionPerformed
        signo = '-';        
        imagenC = "/Imagenes/negativa.png";
        jToggleButton2.setSelected(false);
        jToggleButton3.setSelected(false);
    }//GEN-LAST:event_jToggleButton1ActionPerformed

    private void jToggleButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton2ActionPerformed
      signo='+';
      imagenC = "/Imagenes/positiva.png";
      jToggleButton1.setSelected(false);
      jToggleButton3.setSelected(false);
    }//GEN-LAST:event_jToggleButton2ActionPerformed

    private void jToggleButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton4ActionPerformed
        if(jToggleButton4.isSelected()){
            jlm1.setVisible(true);
            jlm2.setVisible(true);
            repint.resume();
            jlm1.setBounds(30, 430, 20, 20);
            jlm2.setBounds(130, 430, 20, 20);
        }
        else{           
            jlm1.setVisible(false);
            jlm2.setVisible(false);
            repint.suspend();
            jLabel10.repaint();
        }
    }//GEN-LAST:event_jToggleButton4ActionPerformed

    private void jToggleButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jToggleButton3ActionPerformed
      jToggleButton1.setSelected(false); 
      jToggleButton2.setSelected(false);
      
    }//GEN-LAST:event_jToggleButton3ActionPerformed

    private void jd1WindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_jd1WindowClosing
      this.setEnabled(true);// TODO add your handling code here:
    }//GEN-LAST:event_jd1WindowClosing

    private void helpWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_helpWindowClosing
       this.setEnabled(true);
    }//GEN-LAST:event_helpWindowClosing

    private void formWindowClosing(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowClosing
       repint.stop();
      
    }//GEN-LAST:event_formWindowClosing

    private void btnAyudaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAyudaActionPerformed
    help.setBounds(300, 100, 445, 510);
       help.setVisible(true);
    }//GEN-LAST:event_btnAyudaActionPerformed

    private void btnVolverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVolverActionPerformed
    Inicio v = new Inicio();
    v.setVisible(true);
    this.dispose();
    }//GEN-LAST:event_btnVolverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaPrincipal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentanaPrincipal().setVisible(true);
            }
        });
    }
private int  topeCargas = 0;
private char signo = '-';
private double valorCarga = 1E-9;
private String imagenC = "/Imagenes/negativa.png";
private int idCarga;
private boolean parar = false;
boolean clickCarga = false;
boolean clikMira1;
boolean clikMira2;
private int bx;
private int by;
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel angulo;
    private javax.swing.JButton btnAyuda;
    private javax.swing.JButton btnVolver;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fuerzaT;
    private javax.swing.JDialog help;
    private javax.swing.JLabel i;
    private javax.swing.JLabel j;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    public static javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private javax.swing.JToggleButton jToggleButton3;
    private javax.swing.JToggleButton jToggleButton4;
    private javax.swing.JDialog jd1;
    private javax.swing.JLabel jlcarga;
    private javax.swing.JLabel jlm1;
    private javax.swing.JLabel jlm2;
    public static javax.swing.JPanel jp1;
    private javax.swing.JTextField jtV;
    private javax.swing.JLabel nroCarga;
    private javax.swing.JLabel parenti;
    private javax.swing.JLabel parenti2;
    // End of variables declaration//GEN-END:variables

    
  public String valorAprocimado(String cadena){// retorna el valor reducido, despues del . retorna tres sifras+E^n
      String f = null;
      boolean e=false;
      for (int k = 0; k < cadena.length(); k++) {
         char c =cadena.charAt(k);
         if(c=='.'){
           f=f+'.'; 
           k++;
           
           if(k+1<cadena.length()){
              f=f+cadena.charAt(k);
              k++;
           }
           if(k+1<cadena.length()){
              f=f+cadena.charAt(k);
              k++;
           }
           if(k+1<cadena.length()){
              f=f+cadena.charAt(k);
              k++;
           }
           else break;
             for (int l = k; l <cadena.length(); l++) {
                 if(cadena.charAt(l)=='E' || cadena.charAt(l)=='e'){
                     f=f+cadena.substring(l, cadena.length());
                      k=cadena.length();
                      e=true;
                     break;
                 }
             }
             if(!e){
                 break;
             }
         }
         else{
             if(f==null)f = String.valueOf(cadena.charAt(k));
             else
             f=f+cadena.charAt(k);
         }
      }
        return f;

}
    @Override
    public void run() {
        do{           
                 try {
                    
                     repint.sleep(5);
                 } catch (InterruptedException ex) {
                       ex.printStackTrace();
                 }            
             Lineas.pintarLinea(jp1.getGraphics(),jlm1.getX(), jlm1.getY(), jlm2.getX(),jlm2.getY());            
                        
        }while(true);
    }
}
  
